### ISSUE TITLE
[NJ] Essex County

### ISSUE THREAD

**Issue by jloffredo2** [kuriwaki/cvr_harvard-mit_scripts#147]
**Recommendation**: Use data as is.

There are two instances in which the Harvard and MIT data differ and in which precinct results (as verified by https://nj.gov/state/elections/assets/pdf/election-results/2020/2020-official-general-results-president.pdf) show one is correct:

- US PRESIDENT - Joseph R. Biden: 266,819 (Harvard) vs. 266,820 (MIT) -- the precinct results suggest MIT is correct
- US PRESIDENT - Donald J. Trump: 75,475 (Harvard) vs. 75,476 (MIT) -- the precinct results suggest Harvard is correct

Only other deviation to report is:

- US HOUSE (010) - Donald M Payne Jr: both MIT and Harvard match same vote total number, but that number is off by one compared to precinct results.

**Comment by mreece13** [comment]
Good catch, there was some confusion since John Mirrione appears as a legitimate candidate in 010 but is also a Write-In in 009. It should be fixed now.

**Comment by kuriwaki** [comment]
Essex is now in `release` with the fix, along with Hudson county.
