### ISSUE TITLE
[NJ] Cumberland County

### ISSUE THREAD

**Issue by jloffredo2** [kuriwaki/cvr_harvard-mit_scripts#154]
EDIT: No undervotes -- see https://github.com/kuriwaki/cvr_harvard-mit_scripts/issues/154#issuecomment-2318008762

Harvard does not report any results for this county. MIT only reports results for the following, though their numbers are close enough to use as is:

- US PRESIDENT-Joseph R. Biden: 32,437 votes versus 32,742 votes reported in precinct results
- US PRESIDENT-Howie Hawkins: 138 votes versus 139 votes reported in precinct results
- US PRESIDENT-Jo Jorgensen: 395 votes versus 397 votes reported in precinct results
- US PRESIDENT-Donald J. Trump: 28,754 votes versus 28,952 votes reported in precinct results

Nothing is reported by Harvard or MIT for US SENATE or US HOUSE (002). The problem on the MIT side is that candidates do not have party affiliations in the parquet file (i.e., there `NA` values in `party_detailed`), but the individual candidate observations do exist there. The CVR Utils sheet does not any of these individual candidates for these offices in Cumberland County.

**Comment by kuriwaki** [comment]
It appears that the votedabase data https://votedatabase.com/cvr/New%20Jersey/Cumberland/ has removed all undervotes/overvotes before posting. These are dominion json files somehow saved into spreadsheets. All `isVote` values are TRUE and all `undervotes` are zero, which suggested it was prefiltered. The candidate votes are still only about 0.6% off in this medium-sized county.  Pointed out by @JeffreyBLewis

**Comment by mreece13** [comment]
Yes, MIT has a custom script dedicated to Cumberland because of this weirdness. It can be found starting at https://github.com/kuriwaki/cvr_harvard-mit_scripts/blob/36934b9d383c09ae5dc1597191b6f5e5169693d6/code/02_build-medsl/code/functions.R#L504
