### ISSUE TITLE
[NV] Humboldt county

### ISSUE THREAD

**Issue by kuriwaki** [kuriwaki/cvr_harvard-mit_scripts#342]
I missed one Nevada, there is actually Humboldt county, which neither team has yet collected. This is a dominion JSON county of only 8000 voters, https://votedatabase.com/cvr/Nevada/Humboldt/ (use the zip file). I've verified that the Presidential counts will match up exactly. 
@mreece13  would be great to add to `build-medsl` so we can (actually) complete Nevada.

**Comment by mreece13** [comment]
Good catch, addressed in https://github.com/kuriwaki/cvr_harvard-mit_scripts/pull/343

**Comment by kuriwaki** [comment]
Done in #343
