### ISSUE TITLE
[IL] [yellow] McHenry County

### ISSUE THREAD

**Issue by zdj-garai** [kuriwaki/cvr_harvard-mit_scripts#46]
Use the **Harvard**/validated data; the **MIT** data undershoots the reported, official vote counts.

**Comment by kuriwaki** [comment]
I think we can add McHenry in https://github.com/kuriwaki/cvr_harvard-mit_scripts/blob/main/code/04_build-release/metadata/counties_harv.csv for now. The Harvard counts match exactly, it'd be our largest Illinois county by far (though we'd still only have <4% of the state) and it will make Illinois slightly less Republican.

**Comment by mreece13** [comment]
That sounds good to me, still haven't looked into this problem on the MEDSL end.
